import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {categoryRegistry,indicatorRegistry,connectedIndicatorSeries} from '../lib/data/catalog.ts';
import {validateRanking,rankObservations} from '../lib/data/ranking.ts';

test('catalog has exactly 12 stable unique categories and Phase 1 candidate depth',()=>{assert.equal(categoryRegistry.length,12);assert.equal(new Set(categoryRegistry.map(item=>item.id)).size,12);assert.deepEqual(categoryRegistry.map(item=>item.order),[1,2,3,4,5,6,7,8,9,10,11,12]);for(const category of categoryRegistry.slice(0,5)){const count=indicatorRegistry.filter(item=>item.categoryId===category.id).length;assert.ok(count>=3&&count<=5,`${category.id}: ${count}`);}});
test('every home category supplies reusable visual and discovery copy',()=>{for(const category of categoryRegistry){assert.ok(category.icon);assert.ok(category.description.en&&category.description.ko);assert.ok(category.examples.en.length>=2&&category.examples.ko.length>=2);}});
test('only verified total population and two reproducible derived indicators are connected',()=>{const connected=indicatorRegistry.filter(item=>item.status==='CONNECTED');assert.deepEqual(connected.map(item=>item.id),['population_total','population_change_annual','population_change_rate_annual']);for(const item of connected){assert.equal(item.categoryId,'population-household');assert.ok(item.sourceOrg&&item.sourceUrl&&item.license);assert.ok(item.capabilities.includes('citation')&&item.capabilities.includes('export'));}});
test('derived indicator observations preserve provenance and exact formulas',()=>{const change=connectedIndicatorSeries('population_change_annual').at(-1);const rate=connectedIndicatorSeries('population_change_rate_annual').at(-1);assert.equal(change.value,-66501);assert.equal(change.reference_period,'2025');assert.equal(change.derivation,'current - previous');assert.equal(rate.value,-66501/51751065*100);assert.equal(rate.derivation,'(current - previous) / previous × 100');for(const point of [change,rate]){assert.equal(point.quality_status,'VERIFIED');assert.equal(point.source_id,'SP.POP.TOTL');assert.equal(point.region_id,'kr');assert.ok(point.version&&point.source_url);}});
test('blocked candidates cannot leak through connected series',()=>{for(const item of indicatorRegistry.filter(item=>item.status!=='CONNECTED'))assert.deepEqual(connectedIndicatorSeries(item.id),[]);assert.ok(indicatorRegistry.filter(item=>item.status==='BLOCKED').every(item=>item.blockReason));});
test('ranking template rejects unverified, duplicate, mismatched and single-region inputs',()=>{const base={country_id:'kr',region_id:'r1',indicator_id:'x',reference_period:'2025',value:2,unit:'person',quality_status:'VERIFIED',source_org:'official',dataset_name:'d',source_id:'s',source_url:'https://example.org',publication_date:null,ingested_at:'2026-01-01',version:'v1',license:'Open',license_url:'https://example.org/license'};const model={contentId:'rank',indicatorId:'x',referencePeriod:'2025',direction:'desc',observations:[base,{...base,region_id:'r2',value:3}]};assert.equal(validateRanking(model),true);assert.deepEqual(rankObservations(model).map(item=>item.region_id),['r2','r1']);for(const observations of [[base],[base,{...base}],[base,{...base,region_id:'r2',quality_status:'PENDING'}],[base,{...base,region_id:'r2',reference_period:'2024'}]])assert.throws(()=>validateRanking({...model,observations}));});
test('all 12 category names are explicit in all 13 dictionaries',async()=>{const keys=categoryRegistry.map(item=>item.labelKey);for(const locale of ['en','ko','ja','es','pt','de','fr','zh-CN','zh-TW','hi','id','it','vi']){const dictionary=await readFile(new URL(`../lib/i18n/dictionaries/${locale}.ts`,import.meta.url),'utf8');for(const key of keys)assert.ok(dictionary.includes(JSON.stringify(key)+':'),`${locale}: ${key}`);}});
test('discovery home leads with category and only renders connected snapshot numbers',async()=>{const page=await readFile(new URL('../app/page.tsx',import.meta.url),'utf8');assert.ok(page.indexOf('<CategoryCatalog />')<page.indexOf('<DataSnapshot />'));assert.ok(page.indexOf('<DataSnapshot />')<page.indexOf('<KPIBlock />'));for(const id of ['A','B','C'])assert.ok(page.includes(`<AdSlot id="${id}"`));const snapshot=await readFile(new URL('../components/data-snapshot.tsx',import.meta.url),'utf8');assert.match(snapshot,/connectedIds = \["population_total","population_change_annual","population_change_rate_annual"\]/);assert.match(snapshot,/SOURCE REVIEW · NO VALUES/);const ranking=await readFile(new URL('../components/ranking-foundation.tsx',import.meta.url),'utf8');assert.match(ranking,/VERIFICATION GATE/);assert.doesNotMatch(ranking,/rankObservations/);});
