const en = {
  "nav.korea":"INDEX KOREA","hero.eyebrow":"THE WORLD, INDEXED.","hero.line1":"See the world","hero.line2":"through data.","hero.description":"Search, compare, and discover data from around the world. We turn complexity into clear indexes.","hero.free":"100% FREE · NO SIGN-UP · JUST DATA","hero.support":"Explore. Compare. Visualize. Share.",
  "search.heading":"What do you want to know?","search.free":"100% free · No sign-up · Start now","search.support":"Find, compare, visualize, and share.","search.placeholder":"Seoul population, single-person households, Seoul vs Busan...","search.recommended":"SUGGESTED SEARCHES","search.pending":"DATA CONNECTION PENDING","search.pendingText":"Search data for “{query}” is being prepared.","search.contract":"SEARCH CONTRACT V0.2","search.contractText":"Region · indicator · ranking · comparison · question search is being prepared.","search.s1":"Seoul population","search.s2":"Incheon single-person households","search.s3":"Busan housing","search.s4":"Seoul vs Busan",
  "category.kicker":"EXPLORE BY CATEGORY","category.heading":"Explore the world through data","category.population":"Population","category.populationNote":"See how people and places change.","category.household":"Household","category.householdNote":"Read the shape and flow of daily life.","category.housing":"Housing","category.housingNote":"Discover spaces and ways of living.",
  "kpi.kicker":"POPULATION · CORE INDICATORS","kpi.heading":"Korea population at a glance","kpi.status":"TOTAL POPULATION · OFFICIAL DATA CONNECTED","kpi.total":"Total population","kpi.change":"Population change","kpi.age65":"Age 65+","kpi.youth":"Youth population","kpi.period":"Reference period","kpi.source":"Official source","kpi.preparing":"Preparing connection","kpi.disclaimer":"Total population is connected to verified official data. Population change, age 65+, and youth population remain pending until suitable source data is verified.",
  "map.eyebrow":"INDEX KOREA","map.line1":"Discover Korea today","map.line2":"through the map","map.description":"Select a region marker to preview exploration. Official boundaries and statistics appear only after verified data connection.","map.status":"OFFICIAL BOUNDARY DATA PENDING","map.selected":"SELECTED REGION","map.prompt":"Select a region","map.ready":"REGION CONTRACT READY","map.legend1":"Selectable region","map.legend2":"Official data pending","map.seoul":"Seoul","map.daejeon":"Daejeon","map.daegu":"Daegu","map.gwangju":"Gwangju","map.busan":"Busan","map.jeju":"Jeju",
  "popular.kicker":"POPULAR DATA","popular.heading":"Data people explore","popular.side":"Live content appears after data connection.","popular.p1":"Regions with population growth","popular.p2":"Regions with high single-person household share","popular.p3":"Recent population change","popular.p4":"Seoul vs Busan","common.coming":"COMING NEXT",
  "share.eyebrow":"DATA, MADE SHAREABLE.","share.line1":"Take your discoveries","share.line2":"further.","share.description":"Every dataset is designed to be easy to share, compare, and reshape into a new perspective.","share.pending":"SHARING TOOLS · COMING NEXT","share.action":"Share","share.copied":"Link copied","share.failed":"Copy failed","footer.statement":"Make the world understandable.","footer.advertising":"Advertising",
  "timeseries.kicker":"OFFICIAL POPULATION · ANNUAL","timeseries.heading":"Korea population over time","timeseries.description":"Annual total population of the Republic of Korea from the World Development Indicators.","timeseries.region":"REGION","timeseries.korea":"Korea, Rep.","timeseries.range":"Time period","timeseries.all":"ALL","timeseries.years":"Y","timeseries.sourceDetails":"SOURCE & PROVENANCE","timeseries.organization":"Organization","timeseries.dataset":"Dataset","timeseries.indicator":"Indicator","timeseries.reference":"Reference period","timeseries.updated":"INDEX updated","timeseries.license":"License","timeseries.original":"View original source","data.people":"people",
  "ad.label":"Future Ad Placement · Preview only","ad.aria":"Future advertising placement",
} as const;
export default en;
export type TranslationKey = keyof typeof en;
